import turtle
turtle.shape('turtle')
turtle.pencolor('black')
turtle.pensize(3)
turtle.penup()
turtle.goto(-100,100)
turtle.pendown()
for i in range(4):
    turtle.fd(200)
    turtle.right(90)
turtle.penup()
turtle.goto(0,0)
turtle.pencolor('red')
turtle.pendown()
turtle.dot(20)
turtle.penup()
turtle.bk(40)
turtle.pendown()
turtle.dot(20)
turtle.penup()
turtle.fd(80)
turtle.pendown()
turtle.dot(20)
turtle.hideturtle()
turtle.done()
