import turtle
turtle.shape('turtle')
turtle.pensize(25)
turtle.speed(5)
turtle.pencolor('green')
turtle.turtlesize(1.5)
turtle.dot(165,'blue')
turtle.penup()
turtle.goto(0,-95)
turtle.pendown()
turtle.circle(95)
turtle.penup()
turtle.goto(0,-150)
turtle.pendown()
turtle.circle(150)
turtle.done()