import turtle
turtle.shape('turtle')
turtle.pensize(3)
turtle.pencolor('black')
turtle.fillcolor('green')
turtle.speed(0)
turtle.penup()

turtle.goto(0,-200)
turtle.pendown()
turtle.circle(200)
turtle.penup()

turtle.goto(0,40)
turtle.pendown()
turtle.seth(-120)
for i in range(3):
    turtle.forward(75)
    turtle.left(120)
turtle.penup()

turtle.goto(-150,-15)
turtle.seth(-30)
turtle.pendown()
turtle.forward(170)
turtle.seth(30)
turtle.forward(170)
turtle.penup()

turtle.goto(-95,105)
turtle.begin_fill()
turtle.seth(0)
turtle.pendown()
turtle.circle(-25)
turtle.end_fill()
turtle.penup()
turtle.goto(95,105)
turtle.pendown()
turtle.begin_fill()
turtle.circle(-25)
turtle.end_fill()
turtle.hideturtle()
turtle.done()