import turtle
turtle.shape('turtle')
turtle.pensize(3)
turtle.speed(1)
turtle.pencolor('green')
turtle.fillcolor('green')
turtle.begin_fill()
turtle.seth(90)
for i in range(3):
    turtle.circle(-30,180)
    turtle.seth(90)
turtle.circle(90,180)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.forward(90)
turtle.right(-90)
turtle.forward(30)
turtle.right(180)
turtle.pendown()
turtle.forward(140)
turtle.circle(-15,180)
turtle.done()